# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: masterdevice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12masterdevice.proto\"!\n\x0e\x43onnectCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"!\n\x0e\x43onnectMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rHomingCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x1e\n\x0bHomingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15TeleoperationCommand1\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"(\n\x15TeleoperationMessage1\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x15TeleoperationCommand2\x12\r\n\x05\x61ngle\x18\x01 \x03(\x02\"(\n\x15TeleoperationMessage2\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rPowerOffStart\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\" \n\rPowerOffReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0bSaveCommand\x12\r\n\x05\x61ngle\x18\x01 \x03(\x02\"\x0b\n\tSaveReply\"\x1f\n\x0cGravityState\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x0e\n\x0cGravityReply\" \n\rPositionState\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x0f\n\rPositionReply\" \n\rDeleteCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\r\n\x0b\x44\x65leteReply2\xbc\x03\n\x0cmasterdevice\x12+\n\x07\x43onnect\x12\x0f.ConnectCommand\x1a\x0f.ConnectMessage\x12+\n\x0bGravityMode\x12\r.GravityState\x1a\r.GravityReply\x12@\n\x0eTeleoperation1\x12\x16.TeleoperationCommand1\x1a\x16.TeleoperationMessage1\x12\x42\n\x0eTeleoperation2\x12\x16.TeleoperationCommand2\x1a\x16.TeleoperationMessage2(\x01\x12.\n\x0cPositionMode\x12\x0e.PositionState\x1a\x0e.PositionReply\x12&\n\x06Homing\x12\x0e.HomingCommand\x1a\x0c.HomingReply\x12 \n\x04Save\x12\x0c.SaveCommand\x1a\n.SaveReply\x12&\n\x06\x44\x65lete\x12\x0e.DeleteCommand\x1a\x0c.DeleteReply\x12*\n\x08PowerOff\x12\x0e.PowerOffStart\x1a\x0e.PowerOffReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'masterdevice_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTCOMMAND']._serialized_start=22
  _globals['_CONNECTCOMMAND']._serialized_end=55
  _globals['_CONNECTMESSAGE']._serialized_start=57
  _globals['_CONNECTMESSAGE']._serialized_end=90
  _globals['_HOMINGCOMMAND']._serialized_start=92
  _globals['_HOMINGCOMMAND']._serialized_end=124
  _globals['_HOMINGREPLY']._serialized_start=126
  _globals['_HOMINGREPLY']._serialized_end=156
  _globals['_TELEOPERATIONCOMMAND1']._serialized_start=158
  _globals['_TELEOPERATIONCOMMAND1']._serialized_end=198
  _globals['_TELEOPERATIONMESSAGE1']._serialized_start=200
  _globals['_TELEOPERATIONMESSAGE1']._serialized_end=240
  _globals['_TELEOPERATIONCOMMAND2']._serialized_start=242
  _globals['_TELEOPERATIONCOMMAND2']._serialized_end=280
  _globals['_TELEOPERATIONMESSAGE2']._serialized_start=282
  _globals['_TELEOPERATIONMESSAGE2']._serialized_end=322
  _globals['_POWEROFFSTART']._serialized_start=324
  _globals['_POWEROFFSTART']._serialized_end=356
  _globals['_POWEROFFREPLY']._serialized_start=358
  _globals['_POWEROFFREPLY']._serialized_end=390
  _globals['_SAVECOMMAND']._serialized_start=392
  _globals['_SAVECOMMAND']._serialized_end=420
  _globals['_SAVEREPLY']._serialized_start=422
  _globals['_SAVEREPLY']._serialized_end=433
  _globals['_GRAVITYSTATE']._serialized_start=435
  _globals['_GRAVITYSTATE']._serialized_end=466
  _globals['_GRAVITYREPLY']._serialized_start=468
  _globals['_GRAVITYREPLY']._serialized_end=482
  _globals['_POSITIONSTATE']._serialized_start=484
  _globals['_POSITIONSTATE']._serialized_end=516
  _globals['_POSITIONREPLY']._serialized_start=518
  _globals['_POSITIONREPLY']._serialized_end=533
  _globals['_DELETECOMMAND']._serialized_start=535
  _globals['_DELETECOMMAND']._serialized_end=567
  _globals['_DELETEREPLY']._serialized_start=569
  _globals['_DELETEREPLY']._serialized_end=582
  _globals['_MASTERDEVICE']._serialized_start=585
  _globals['_MASTERDEVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
