# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GRPC.stubs.masterdevice_pb2 as masterdevice__pb2


class masterdeviceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/masterdevice/Connect',
                request_serializer=masterdevice__pb2.ConnectCommand.SerializeToString,
                response_deserializer=masterdevice__pb2.ConnectMessage.FromString,
                )
        self.GravityMode = channel.unary_unary(
                '/masterdevice/GravityMode',
                request_serializer=masterdevice__pb2.GravityState.SerializeToString,
                response_deserializer=masterdevice__pb2.GravityReply.FromString,
                )
        self.Teleoperation1 = channel.unary_unary(
                '/masterdevice/Teleoperation1',
                request_serializer=masterdevice__pb2.TeleoperationCommand1.SerializeToString,
                response_deserializer=masterdevice__pb2.TeleoperationMessage1.FromString,
                )
        self.Teleoperation2 = channel.stream_unary(
                '/masterdevice/Teleoperation2',
                request_serializer=masterdevice__pb2.TeleoperationCommand2.SerializeToString,
                response_deserializer=masterdevice__pb2.TeleoperationMessage2.FromString,
                )
        self.PositionMode = channel.unary_unary(
                '/masterdevice/PositionMode',
                request_serializer=masterdevice__pb2.PositionState.SerializeToString,
                response_deserializer=masterdevice__pb2.PositionReply.FromString,
                )
        self.Homing = channel.unary_unary(
                '/masterdevice/Homing',
                request_serializer=masterdevice__pb2.HomingCommand.SerializeToString,
                response_deserializer=masterdevice__pb2.HomingReply.FromString,
                )
        self.Save = channel.unary_unary(
                '/masterdevice/Save',
                request_serializer=masterdevice__pb2.SaveCommand.SerializeToString,
                response_deserializer=masterdevice__pb2.SaveReply.FromString,
                )
        self.Delete = channel.unary_unary(
                '/masterdevice/Delete',
                request_serializer=masterdevice__pb2.DeleteCommand.SerializeToString,
                response_deserializer=masterdevice__pb2.DeleteReply.FromString,
                )
        self.PowerOff = channel.unary_unary(
                '/masterdevice/PowerOff',
                request_serializer=masterdevice__pb2.PowerOffStart.SerializeToString,
                response_deserializer=masterdevice__pb2.PowerOffReply.FromString,
                )


class masterdeviceServicer(object):
    """The greeting service definition.
    """

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GravityMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teleoperation1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teleoperation2(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PositionMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Homing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Save(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PowerOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_masterdeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=masterdevice__pb2.ConnectCommand.FromString,
                    response_serializer=masterdevice__pb2.ConnectMessage.SerializeToString,
            ),
            'GravityMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GravityMode,
                    request_deserializer=masterdevice__pb2.GravityState.FromString,
                    response_serializer=masterdevice__pb2.GravityReply.SerializeToString,
            ),
            'Teleoperation1': grpc.unary_unary_rpc_method_handler(
                    servicer.Teleoperation1,
                    request_deserializer=masterdevice__pb2.TeleoperationCommand1.FromString,
                    response_serializer=masterdevice__pb2.TeleoperationMessage1.SerializeToString,
            ),
            'Teleoperation2': grpc.stream_unary_rpc_method_handler(
                    servicer.Teleoperation2,
                    request_deserializer=masterdevice__pb2.TeleoperationCommand2.FromString,
                    response_serializer=masterdevice__pb2.TeleoperationMessage2.SerializeToString,
            ),
            'PositionMode': grpc.unary_unary_rpc_method_handler(
                    servicer.PositionMode,
                    request_deserializer=masterdevice__pb2.PositionState.FromString,
                    response_serializer=masterdevice__pb2.PositionReply.SerializeToString,
            ),
            'Homing': grpc.unary_unary_rpc_method_handler(
                    servicer.Homing,
                    request_deserializer=masterdevice__pb2.HomingCommand.FromString,
                    response_serializer=masterdevice__pb2.HomingReply.SerializeToString,
            ),
            'Save': grpc.unary_unary_rpc_method_handler(
                    servicer.Save,
                    request_deserializer=masterdevice__pb2.SaveCommand.FromString,
                    response_serializer=masterdevice__pb2.SaveReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=masterdevice__pb2.DeleteCommand.FromString,
                    response_serializer=masterdevice__pb2.DeleteReply.SerializeToString,
            ),
            'PowerOff': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerOff,
                    request_deserializer=masterdevice__pb2.PowerOffStart.FromString,
                    response_serializer=masterdevice__pb2.PowerOffReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'masterdevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class masterdevice(object):
    """The greeting service definition.
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/Connect',
            masterdevice__pb2.ConnectCommand.SerializeToString,
            masterdevice__pb2.ConnectMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GravityMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/GravityMode',
            masterdevice__pb2.GravityState.SerializeToString,
            masterdevice__pb2.GravityReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Teleoperation1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/Teleoperation1',
            masterdevice__pb2.TeleoperationCommand1.SerializeToString,
            masterdevice__pb2.TeleoperationMessage1.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Teleoperation2(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/masterdevice/Teleoperation2',
            masterdevice__pb2.TeleoperationCommand2.SerializeToString,
            masterdevice__pb2.TeleoperationMessage2.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PositionMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/PositionMode',
            masterdevice__pb2.PositionState.SerializeToString,
            masterdevice__pb2.PositionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Homing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/Homing',
            masterdevice__pb2.HomingCommand.SerializeToString,
            masterdevice__pb2.HomingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Save(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/Save',
            masterdevice__pb2.SaveCommand.SerializeToString,
            masterdevice__pb2.SaveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/Delete',
            masterdevice__pb2.DeleteCommand.SerializeToString,
            masterdevice__pb2.DeleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PowerOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/masterdevice/PowerOff',
            masterdevice__pb2.PowerOffStart.SerializeToString,
            masterdevice__pb2.PowerOffReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
